const checkboxItems = [
  { name: "outgoing", value: 'outgoing' },
  { name: 'driven', value: 'driven' },
  { name: 'assertive', value: 'assertive' },
  { name: 'sociable', value: 'sociable' },
  { name: 'extraverted', value: 'extraverted' },
  { name: 'indirect', value: 'indirect' },
  { name: 'loyal', value: 'loyal' },
  { name: 'introverted', value: 'introverted' },
  { name: 'talkative', value: 'talkative' },
  { name: 'empathetic', value: 'empathetic' },
  { name: 'agreeable', value: 'agreeable' },
  { name: 'warm- hearted', value: 'warm-hearted' },
  { name: 'collaborative', value: 'collaborative' },
  { name: 'independent', value: 'independent' },
  { name: 'determined', value: 'determined' },
  { name: 'direct', value: 'direct' },
  { name: 'unemotional', value: 'unemotional' },
  { name: 'responsible', value: 'responsible' },
  { name: 'level-headed', value: 'level-headed' },
  { name: 'structure- freak', value: 'structure-freak' },
  { name: 'perfectionist', value: 'perfectionist' },
  { name: 'risk-taker', value: 'risk-taker' },
  { name: 'flexible', value: 'flexible' },
  { name: 'risk-averse', value: 'risk-averse' },
  { name: 'passionate', value: 'passionate' },
  { name: 'thorough', value: 'thorough' },
  { name: 'intuitive', value: 'intuitive' }]
  
module.exports = checkboxItems